# Generated by Django 4.0 on 2022-12-04 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_appointment_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Patient',
            new_name='patient',
        ),
    ]
