# Generated by Django 4.0 on 2022-12-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_appointment_department_appointment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='homepage_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
