# Generated by Django 4.0 on 2022-12-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_medicament_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(default='2022-06-12'),
            preserve_default=False,
        ),
    ]
