# Generated by Django 4.0 on 2022-12-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_appointment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='emrgency_contact_number',
            new_name='emergency_contact_number',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='martial_status',
            new_name='marital_status',
        ),
    ]
