# Generated by Django 4.0 on 2022-12-06 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_adress_doctor_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='department_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='specialization_id',
            new_name='specialization',
        ),
    ]
