# Generated by Django 4.0 on 2022-12-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_department_id_doctor_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='department',
            new_name='department_id',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='schedule',
            new_name='schedule_details',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='specialization',
            new_name='specialization_id',
        ),
    ]
