# Generated by Django 4.0 on 2022-12-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_department_doctor_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
